name: simple_string_utils
description: A simple Dart package that provides utility functions for string manipulation such as uppercase and lowercase conversion.
version: 1.0.0
repository: https://github.com/umario-chi/stringutils

environment:
  sdk: ^3.11.5

# Add regular dependencies here.
# dependencies:
  # path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
